# Generated by Django 4.1.3 on 2022-12-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hesap',
            name='resim',
            field=models.FileField(blank=True, default='img/default.webp', upload_to='hesaplar/'),
        ),
    ]
