# Generated by Django 4.1.3 on 2022-12-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_hesap_takipci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hesap',
            name='resim',
            field=models.FileField(blank=True, default='default.webp', upload_to='hesaplar/'),
        ),
    ]
